micronaut:
  application:
    name: pix
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  server:
    port: 8089
  channels:
    pix: #nome do canal em GrpcClientFactory
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5

jpa:
  default:
    entity-scan:
      packages: 'net.andreinc.mn.crud.backend.*'

jackson:
  serialization:
    writeDatesAsTimestamps: false